### ISSUE TITLE
Error after original connection

### ISSUE THREAD

**Issue by mwelby** [rousan/linkedin-auto-connect#16]
Hi - the script worked for 100 connections and stated too many requests and now it is throwing an error as below:

  Connecting to the LinkedIn server..(node:7632) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at C:\Users\MYPC\AppData\Roaming\npm\node_modules\linkedin-auto-connect\lib\scraper.js:25:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mwelby** [comment]
OK the error above has cleared after connecting directly and not through a VPN.

I am now getting the "error too many requests"

This appeared after 100 connections.

Is there a way around this limit?

**Comment by alkhachatryan** [comment]
> OK the error above has cleared after connecting directly and not through a VPN.
> 
> I am now getting the "error too many requests"
> 
> This appeared after 100 connections.
> 
> Is there a way around this limit?

no

**Comment by amanrashm** [comment]
after getting connected it's not doing anything can anyone here help
